# Generated by Django 3.2.6 on 2021-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=500)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
